apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: jupyter-pvc
  namespace: thetrains
  labels:
    app: jupyter
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi
  storageClassName: rook-ceph-block